### ISSUE TITLE
User can search for entries

### ISSUE THREAD

**Issue by nathan-uch** [nathan-uch/code-journal#9]
## 💰 Motivation

When a user wants to quickly find an entry they should be able to type in a search box and best results will appear.

## 📐 Plan

Allow users to quickly search for specific entries

## 🖼️ Wireframes
![Screen Shot 2022-06-02 at 16 39 51](https://user-images.githubusercontent.com/68994507/171757884-66666700-13e7-4a98-8b32-03b4eeb561cc.png)
![Screen Shot 2022-06-02 at 16 40 01](https://user-images.githubusercontent.com/68994507/171757891-d12cf423-f7f9-4d45-adb1-935fe4db2891.png)
![Screen Shot 2022-06-02 at 16 40 10](https://user-images.githubusercontent.com/68994507/171757893-dc702b7a-1814-4f3f-ba38-e02fda8ec423.png)
![Screen Shot 2022-06-02 at 16 40 24](https://user-images.githubusercontent.com/68994507/171757894-5c1371d3-3cd5-40f5-be50-221851c9c4c1.png)

## ✅ Task List

- [x] Create a search input textbox at the top of the page with a placeholder.
- [x] Style the search box to match with the web page.
- [x] Add an event listener of input on the search box.
- [x] Compare all current entries to the search box text and hide all non-related entries from the page.
- [x] Make text and search results NOT case-sensitive.
- [x] If no matching entries are found, hide all entries and display a message on the page.
- [x] If search box is empty, display all entries.
- [x] Remove all CSS styling that had not affect or was otherwise unnecessary.
- [x] Test functionality again in a private browsing session.
- [x] Fix all errors.
